sudo: true

language: generic

matrix:
  include:
    -
      env:
        - ID=api/lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/api
        - INSTALL='yarn install'
        - ACTION='yarn lint'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=explorer/lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/explorer
        - INSTALL='yarn install'
        - ACTION='yarn lint'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=processing/lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/processing
        - INSTALL=''
        - ACTION='./gradlew --no-daemon ktlintCheck'
      language: generic
    -
      env:
        - ID=processing/kafka-streams/unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/processing
        - INSTALL=''
        - ACTION='./gradlew --no-daemon :kafka-streams:test'
      language: generic

before_install:
  - './.travis/before-install.sh'

install:
  - cd $PROJECT_DIR
  - eval $INSTALL

script:
  - cd $PROJECT_DIR
  - eval $ACTION

after_success:
  - ./.travis/after-success-sh
  #- if [[ "$TRAVIS_BRANCH" == "develop" ]]; then
  #  ./.travis/after-success.sh
  #  fi

notifications:
  email: false
