sudo: true
language: generic
services:
  - redis-server
git:
  submodules:
    false
matrix:
  include:
    -
      env: PROJECT=apps/ethvm
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/ethvm-e2e-test
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/server-unit-test
      language: node_js
      node_js:
        - "10"
    -
      env: PROJECT=apps/server
      language: node_js
      node_js:
        - "10"

before_install:
  - ./.travis/build-condition.sh .travis/build-condition.sh
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/ethvm-e2e-test" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/server-unit-test" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'

install:
  - yarn install

before_script:
  - 'if [ $PROJECT = "apps/ethvm" ]; then cd $TRAVIS_BUILD_DIR/apps/ethvm; fi'
  - 'if [ $PROJECT = "apps/server" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/ethvm-e2e-test" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'
  - 'if [ $PROJECT = "apps/server-unit-test" ]; then cd $TRAVIS_BUILD_DIR/apps/server; fi'

script:
  - 'if [ $PROJECT = "apps/server" ]; then yarn lint;  fi'
  - 'if [ $PROJECT = "apps/ethvm-e2e-test" ]; then yarn test:e2e;  fi'
  - 'if [ $PROJECT = "apps/server-unit-test" ]; then yarn test:unit;  fi'
