sudo: true
language: generic
git:
  submodules:
    false

matrix:
  include:
    -
      env:
        - ID=api-lint
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn lint'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=api-unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn test:unit'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=api-e2e-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/server
        - INSTALL='yarn install'
        - ACTION='yarn test:e2e'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=explorer-unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/ethvm
        - INSTALL='yarn install'
        - ACTION='yarn test:unit'
      language: node_js
      node_js:
        - "10"
    -
      env:
        - ID=kafka-streams-unit-tests
        - PROJECT_DIR=$TRAVIS_BUILD_DIR/apps/kafka-streams
        - INSTALL=''
        - ACTION='./gradlew --no-daemon test'
      language: generic

before_install:
  - ./.travis/before-install.sh

install:
  - cd $PROJECT_DIR
  - eval $INSTALL

script:
  - cd $PROJECT_DIR
  - eval $ACTION

deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/.travis/docker-push.sh
  on:
    branch: master
