files:
  - source: /v2/src/translations/**/en_US.json
    translation: /%original_path%/%locale_with_underscore%.json
targets:
  - name: en_US
    sources:
      - develop/v2/src/translations/**/en_US.json
    file: develop/%original_path%/%locale_with_underscore%.json
    format: xliff
