version: '3.6'

volumes:
  ethereumj-volume:

services:

  ethereumj:
    build:
      context: ./apps/ethereumj
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ethereumj-volume:/ethj
      - ./docker/config/ethereumj/:/ethereumj/ethereumj-core/src/main/resources/
    networks:
      back:
        ipv4_address: 172.25.0.102
    command: ./gradlew --no-daemon run -PmainClass=io.enkrypt.kafka.${ETH_NETWORK}

  bolt:
    build:
      context: ./apps/bolt
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - back
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      MONGO_URI: 'mongodb://mongodb:27017/ethvm_local'
