version: "3.6"

networks:
  web:
    external: true
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  redis-volume:
  mongodb-volume:
  ethereumj-volume:
  kafka-volume-1:
  zookeeper-volume:

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config/traefik/traefik.dev.toml:/etc/traefik/traefik.toml
    networks:
      - web
      - back
    ports:
      - 80:80
      - 81:81

  ethvm:
    build:
      context: ./apps/ethvm
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./apps/ethvm:/var/ethvm
      - ./apps/common:/var/common
    networks:
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ethvm.${DOMAIN}"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=ethvm"
      - "traefik.port=8080"

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./apps/server:/var/ethvm-server
      - ./apps/common:/var/common
    depends_on:
      - redis
      - mongodb
    networks:
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:api.ethvm.${DOMAIN}"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:http://ethvm.${DOMAIN}||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=server"
      - "traefik.port=3000"
    environment:
      - ETHVM_DATA_STORE_REDIS_HOST=redis
      - ETHVM_ETH_TRIE_DB_REDIS_HOST=redis

  redis:
    image: redis:${REDIS_VERSION}-alpine
    restart: unless-stopped
    volumes:
      - redis-volume:/data
    networks:
      - back
    ports:
      - 6379:6379
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:redis.ethvm.${DOMAIN}"
      - "traefik.port=6379"
      - "traefik.backend=redis"

  mongodb:
    image: enkryptio/mongodb-dev:${MONGODB_VERSION}
    restart: unless-stopped
    volumes:
      - mongodb-volume:/data/db
      - ./datasets:/datasets
    networks:
      - back
    ports:
      - 27017:27017
    command: "mongod --bind_ip 0.0.0.0 --replSet rs0 --quiet --slowms 10000"
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:mongo.ethvm.${DOMAIN}"
      - "traefik.port=27017"
      - "traefik.backend=mongodb"

  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    volumes:
      - zookeeper-volume:/var/lib/zookeeper
    networks:
      back:
        ipv4_address: 172.25.0.103
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: "server.1=zookeeper:2888:3888"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-1:
    image: confluentinc/cp-kafka:${CP_VERSION}
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - kafka-volume-1:/var/lib/kafka
    networks:
      back:
        ipv4_address: 172.25.0.104
    ports:
      - 9091:9091
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka-1"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9091"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_MESSAGE_MAX_BYTES: "2000000000"

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-1
    networks:
      back:
        ipv4_address: 172.25.0.107
    ports:
      - 8081:8081
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-schema-registry.ethvm.${DOMAIN}"
      - "traefik.port=8081"
      - "traefik.backend=kafka-schema-registry"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-1:9091"
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: "INFO"
      SCHEMA_REGISTRY_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"

  kafka-connect:
    image: confluentinc/cp-kafka-connect:${CP_VERSION}
    restart: unless-stopped
    depends_on:
      - zookeeper
      - kafka-1
      - mongodb
      - kafka-schema-registry
    networks:
      - back
    ports:
      - 8083:8083
    volumes:
      - ./apps/processing/kafka-connect/libs:/usr/share/enkryptio
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-connect.ethvm.${DOMAIN}"
      - "traefik.port=8083"
      - "traefik.backend=kafka-connect"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-1:9091
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "kafka-connect-avro"
      CONNECT_CONFIG_STORAGE_TOPIC: "kafka-connect-avro-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "kafka-connect-avro-offsets"
      CONNECT_OFFSET_COMMIT_INTERVAL_MS: 1000
      CONNECT_STATUS_STORAGE_TOPIC: "kafka-connect-avro-status"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components,/usr/share/enkryptio

  # ----------------------------------------
  # Helpers (Components that assists in dev)
  # ----------------------------------------

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:${CP_VERSION}
    networks:
      - back
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9091
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-schema-registry

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:${KAFKA_UI_VERSION}
    networks:
      - back
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-schema-registry
      - kafka-rest-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=kafka-topics-ui"
      - "traefik.port=8000"

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:${KAFKA_UI_VERSION}
    networks:
      - back
    ports:
      - 8003:8000
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-connect-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=kafka-connect-ui"
      - "traefik.port=8003"

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:${ZOONAVIGATOR_VERSION}
    networks:
      - back
    environment:
      SERVER_HTTP_PORT: 9000
    depends_on:
      - zookeeper

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:${ZOONAVIGATOR_VERSION}
    networks:
      - back
    ports:
      - 8004:8000
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
      - zoonavigator-api
    depends_on:
      - zoonavigator-api
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:zookeeper-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=zoonavigator-api"
      - "traefik.port=8004"
