version: '3.6'

networks:
  web:
    external: true
  back:
    external: false

services:

  traefik:
    image: traefik:1.6.2-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - web
      - back
    ports:
      - "80:80"
      - "8080:8080"

  ethvm:
    build: ./
    restart: unless-stopped
    networks:
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ethvm.lan"
      - "traefik.port=8080"
      - "traefik.backend=ethvm"
    environment:
      - ETHVM_HOST=0.0.0.0
      - ETHVM_PORT=8080
      - ETVHM_DOCKER=true

  ethvm_socket_server:
    image: enkryptio/ethvm-socket-server:latest
    restart: unless-stopped
    depends_on:
      - geth
      - redis
      - rethinkdb
    networks:
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ws.ethvm.lan"
      - "traefik.port=8080"
      - "traefik.backend=ethvm_socket_server"
    environment:
      - ETHVM_RETHINKDB_URL="rethinkdb://rethinkdb:29015"
      - ETHVM_REDIS_URL="redis:6379"
      - ETHVM_RPC_HOST="geth"
      - ETHVM_RPC_PORT="8545"

  redis:
    image: redis:4.0.9-alpine
    restart: unless-stopped
    networks:
      - back

  rethinkdb:
    image: enkryptio/rethinkdb:latest
    restart: unless-stopped
    networks:
      - back
    ports:
      - "29015:29015"

  geth:
    image: enkryptio/go-ethereum:latest
    restart: unless-stopped
    depends_on:
      - rethinkdb
    volumes:
      - ./docker/volumes/geth/:/geth
    networks:
      - back
    entrypoint: geth --testnet --datadir /geth/ --syncmode full --ethvm --ethvm.remote --rpc --rpcaddr "0.0.0.0" --rpcport 9545 --gcmode archive
    environment:
      - RETHINKDB_URL="rethinkdb://admin:1234@rethinkdb:29015"


