version: '2.4'

services:
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:${CP_VERSION}
    networks:
      - back
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-1:9091
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-schema-registry
    cpu_shares: 256

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:${KAFKA_UI_VERSION}
    networks:
      - back
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-schema-registry
      - kafka-rest-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=kafka-topics-ui"
      - "traefik.port=8000"
    cpu_shares: 256

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:${KAFKA_UI_VERSION}
    networks:
      - back
    ports:
      - 8003:8000
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:kafka-connect-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=kafka-connect-ui"
      - "traefik.port=8003"
    cpu_shares: 256

  zoonavigator-api:
    image: elkozmon/zoonavigator-api:${ZOONAVIGATOR_VERSION}
    networks:
      - back
    environment:
      SERVER_HTTP_PORT: 9000
    depends_on:
      - zookeeper
    cpu_shares: 256

  zoonavigator-web:
    image: elkozmon/zoonavigator-web:${ZOONAVIGATOR_VERSION}
    networks:
      - back
    ports:
      - 8004:8000
    environment:
      API_HOST: "zoonavigator-api"
      API_PORT: 9000
    links:
      - zoonavigator-api
    depends_on:
      - zoonavigator-api
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:zookeeper-ui.ethvm.${DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=zoonavigator-api"
      - "traefik.port=8004"
    cpu_shares: 256
