version: '3.7'

volumes:

  ethvm-kafka-processing:
    external: false

services:

  # ///////////////////////////////////////////////////////
  # Front Services
  # ///////////////////////////////////////////////////////

  api:
    environment:
      INSTA_MINING: 'true'

  # ///////////////////////////////////////////////////////
  # Processing
  # ///////////////////////////////////////////////////////

  ethvm-kafka-processing:
    build:
      context: ./apps/processing
      dockerfile: ./kafka-streams/Dockerfile
    restart: unless-stopped
    depends_on:
      - kafka-1
      - zookeeper
      - kafka-schema-registry
    networks:
      - net
    volumes:
      - ethvm-kafka-processing:/var/lib/kafka-streams
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9091
      KAFKA_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
      WEB3_WS_URL: ws://parity:8546
      KAFKA_STREAMS_STATE_DIR: /var/lib/kafka-streams
