[footprint]
tracing = "on"
pruning = "archive"

[network]
port = 30303

[rpc]
port = 8545
interface = "all"
apis = ["web3", "eth", "net", "pubsub", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

[websockets]
port = 8446
interface = "all"
apis = ["web3", "eth", "net", "pubsub", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
