defaultEntryPoints = ["http","https"]
debug = false
logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
    
[kubernetes]

[ping]
  entryPoint = "http"

[accessLog]
    
[acme]
  email = "it@enkryptio.com"
  storage = "/etc/traefik/acme/account"
  acmeLogging = true
  entryPoint = "https"
  OnHostRule = true
  [acme.httpChallenge]
    entryPoint="http"
