---

- name: Check if API instances are created on GCP
  command: "gcloud compute instances list --filter='name:{{ name }}-{{ gcp.api.name }}' --format='value(status)'"
  register: instance_created
  changed_when: false
  ignore_errors: yes

- name: Delete API instances on GCP
  command: "gcloud compute instances delete {{ name }}-{{ gcp.api.name }}"
  changed_when: false
  when: instance_created.stdout != ""
