---

- name: Check if EthereumJ instances are created on GCP
  command: "gcloud compute instances list --filter='name:{{ name }}-{{ gcp.ethj.name }}' --format='value(status)'"
  register: instance_created
  changed_when: false
  ignore_errors: yes

- name: Delete EthereumJ instances on GCP
  command: "gcloud compute instances delete {{ name }}-{{ gcp.ethj.name }}"
  changed_when: false
  when: instance_created.stdout != ""
