---

- name: Check if Google Cloud SDK is installed
  command: gcloud version
  register: gcloud_installed
  changed_when: false
  ignore_errors: yes

- fail:
    msg: "Please make sure Google Cloud SDK is installed before executing the role."
  when: gcloud_installed is not successful

- name: API Server | Deletion
  import_tasks: api.yaml

- name: Kafka Server | Deletion
  import_tasks: kafka.yaml

- name: EthereumJ Server | Deletion
  import_tasks: ethj.yaml

- name: MongoDb Server | Deletion
  import_tasks: mongo.yaml

- name: Bolt Server | Deletion
  import_tasks: bolt.yaml

- name: Clean GCP inventory file
  file:
    state: absent
    path: "./{{ gcp.inventory_output_file }}"
