topics:

  - name: canonical-blocks
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-uncles
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-transactions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-receipts
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-traces
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-ether-balances
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: ether-balances
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-gas-prices
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-gas-used
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-transaction-fees
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-metrics
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-block-metrics
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-fee-block-metrics
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact


  - name: canonical-chain
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: canonical-blocks
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: canonical-blocks-concurrent
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: canonical-transactions
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: canonical-transactions-concurrent
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-ether-balance-deltas
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-ether-balance-deltas
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-gas-prices
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-gas-used
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: transaction-fees
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: ether-balance-deltas
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: ether-balances
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact


  - name: contract-metadata
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-destructions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-creations
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: pending-transactions
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: address-tx-events
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: address-tx-counts
    replicationFactor: 1
    partitions: 12
    config:
      retention.ms: -1

  - name: miner-list
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: contract-creator-list
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-metrics-by-block
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: block-metrics-by-day
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: aggregate-block-metrics-by-day
    replicationFactor: 1
    partitions: 12
    config:
      cleanup.policy: compact

  - name: eth-tokens-list
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: eth-tokens-list-by-symbol
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: raw-exchange-rates
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: token-exchange-rates
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact

  - name: processing-metadata
    replicationFactor: 1
    partitions: 1
    config:
      cleanup.policy: compact
