name: add to mewbuilds

on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags-ignore:
      - '*'

jobs:
  mewbuilds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-
      - name: move to ./newclient
        run: cd ./newclient

      - name: yarn install
        run: yarn install

      - name: yarn lint
        run: yarn install && yarn lint

      - name: build
        run: yarn install && yarn apollo:codegen && yarn build

      - name: post build
        if: github.base_ref == ''
        env:
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          VIRUS_TOTAL_API_KEY: ${{secrets.VIRUS_TOTAL_API_KEY}}
          GITHUB_TOKEN: ${{secrets.MEW_API_KEY}}
        run: |
          cd ./newclient
          pip install --user awscli
          aws s3 sync --delete --acl public-read dist/ s3://mewbuilds/build/$GITHUB_SHA
          aws s3 cp s3://mewbuilds/build/$GITHUB_SHA/service-worker.js s3://mewbuilds/build/$GITHUB_SHA/service-worker.js \
            --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type application/javascript --acl public-read
          aws s3 cp s3://mewbuilds/build/$GITHUB_SHA/index.html s3://mewbuilds/build/$GITHUB_SHA/index.html \
            --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type text/html --acl public-read
          cd dist && zip -r ../ethVM-$GITHUB_SHA.zip * && cd ..
          VIRUS_TOTAL_URL=`curl -s -F "file=@ethVM-$GITHUB_SHA.zip" -F apikey=${VIRUS_TOTAL_API_KEY} https://www.virustotal.com/vtapi/v2/file/scan | jq --raw-output '.permalink'`
          curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
            -d "{\"body\": \"Copy of this build can be found at <br/>https://www.mewbuilds.com/build/${GITHUB_SHA}/index.html<br/> \
                            Virus Total analysis <br/> \
                            $VIRUS_TOTAL_URL\"}" \
                            "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/comments"
