name: deploy live

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: verify tag
        run: |
          echo $GITHUB_SHA
          git branch --contains $GITHUB_SHA
          git branch --contains $GITHUB_SHA | sed -e 's/^[ \t *]*//' | grep '^master$'
          git checkout $GITHUB_SHA

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{env.NODE_VERSION}}-

      - name: yarn install
        run: cd ./newclient && yarn install

      - name: yarn lint
        run: cd ./newclient && yarn install && yarn lint

      - name: build
        run: cd ./newclient && yarn install && yarn apollo:codegen && yarn build

      - name: Get release tag
        id: get_release_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: deploy to sentry
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_TOKEN}}
          SENTRY_ORG: myetherwallet-inc
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          TAG=${{ steps.get_release_tag.outputs.VERSION }}
          RELEASE=${TAG//v/}
          sentry-cli releases new -p ethvm-web $RELEASE
          sentry-cli releases -p ethvm-web files $RELEASE upload-sourcemaps ./newclient/dist/sourcemaps --url-prefix 'https://www.ethvm.com/sourcemaps' --rewrite --validate
          sentry-cli releases set-commits $RELEASE --auto
          sentry-cli releases finalize $RELEASE
