---

- name: Set Bolt GCP instances names
  debug:
    msg: "{{ name }}-{{ gcp.bolt.name }}-{{ '%d'|format(item|int) }}"
  register: instance_names
  with_sequence: "start=1 end={{ gcp.bolt.instances }}"

- name: Check if Bolt GCP instances has been created
  command: "gcloud compute instances list --filter='name:{{ name }}-{{ gcp.bolt.name }}' --format='value(status)'"
  register: instance_created
  changed_when: false
  ignore_errors: yes

- name: Create Bolt instances on GCP
  loop: "{{ hostvars.localhost.instance_names.results | map(attribute='msg') | list }}"
  loop_control:
    index_var: i
  command: >
    gcloud compute instances create
    {{ item }}
    --zone="{{ gcp.zone }}"
    --image-family="{{ gcp.image_family }}"
    --image-project="{{ gcp.image_project }}"
    --machine-type="{{ gcp.bolt.machine_type }}"
    --boot-disk-size="{{gcp.bolt.disks.size }}"
    --boot-disk-type="{{ gcp.bolt.disks.type }}"
    --metadata-from-file=ssh-keys="{{ gcp.ssh_private_key_file }}"
    --tags="{{ gcp.bolt.name }}"
  changed_when: false
  when: instance_created.stdout == ""

- name: Start Bolt instances if it's on TERMINATED status
  command: gcloud compute instances start "{{ name }}-{{ gcp.bolt.name }}"
  changed_when: false
  when: instance_created.stdout == "TERMINATED"
